version: '3.8'

services:
  database:
    container_name: database-container
    image: postgres:latest
    expose:
      - 5432
    env_file:
      - ./database/prod.env
    networks:
      - database-backend
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  backend-prod:
    container_name: backend-container-prod
    image: bijaydockerhub/react-express-app:backend-${BACKEND_TAG}
    env_file:
      - ./backend/prod.env
    ports:
      - "4000:3000"
    networks:
      - database-backend
    depends_on:
      - database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always


  frontend-prod:
    container_name: frontend-container-prod
    image: bijaydockerhub/react-express-app:front-${FRONTEND_TAG}
    ports:
      - "5000:80"
    restart: always

networks:
  database-backend:
    driver: bridge

volumes:
  db-data: 
