name: backend-workflow

on:
    push:
        branches:
            - main
        paths:
            - app/backend/**
            
jobs:
    build-and-push-image:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4.2.2
              with:
                fetch-depth: 2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            
            - name: Build and push to DockerHub
              uses: docker/build-push-action@v6
              with:
                context: app/backend/.
                push: true
                tags: bijaydockerhub/react-express-app:backend-${{ GITHUB_SHA::7 }}
            
            - name: Artifact commit sha
              run: |
                echo "This: ${{ GITHUB_SHA::7 }}"
                echo "${{ GITHUB_SHA::7 }}" > commit_sha.txt
                cat commit_sha.txt

    deploy:
      runs-on: ubuntu-latest
      needs: build-and-push-image
      steps:    
        - name: Deploy
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_KEY }}
          run: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            echo "Successfully deployed"
            echo "SHA short: ${{env.SHA_SHORT}}"
            ssh -A -tt -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p 22 adminuser@${{ secrets.SERVER_ADDRESS }} "cd app/ && bash deploy.sh --backend --backend-tag $SHA_SHORT"
